# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04cfb3e5042a721adc7b95e78e4f4dffdaf962b2dfe6340ae6474937eee7a9ed0f2108c1d8184abe838634f7e1619b82e0b6e7038fae9ff9a58cf48c03160d97

test:
  secret_key_base: 29704cd62f6e452f3dd0196b75ae332d4bf383e9bfeceaf9ae76b942f2d9fbf5a148cbc6d9a718eacde686b1e528670066920a69dd619114ceb4f3d7d1fc9148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
